apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider-currency-exchange-pj
  namespace: portal-privado
spec:
  provider: aws
  secretObjects:
    - secretName: secrets-dev-bff-currency-exchange-pj
      type: Opaque
      data:
        - objectName: inner-bcl-apikey
          key: bcl-apikey
        - objectName: inner-acl-apikey
          key: acl-apikey
  parameters:
    objects: |
      - objectName: "APIKey/dev/inner/bcl/tesoreria"
        objectType: secretsmanager
        jmesPath:
          - path: clientsecret
            objectAlias: inner-bcl-apikey
      - objectName: "APIKey/dev/inner/acl/tesoreria"
        objectType: secretsmanager
        jmesPath:
          - path: aclapikey
            objectAlias: inner-acl-apikey
      

